name: Run Prettier & Lint

on:
  pull_request:
  push:
    branches: [ main, devops, QA ] # adjust branches as needed

jobs:
  check-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # change if your project uses another version

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Lint
        run: npm run lint
